const path = require('path');

const PAPER_WORKTREE_PATH = process.env.PAPER_WORKTREE_PATH || path.resolve(__dirname, '..', 'dex-trading-bot-paper');

module.exports = {
  apps: [
    {
      name: 'dex-bot',
      script: 'src/index.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      kill_timeout: 10000,
      listen_timeout: 15000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        BOT_PROFILE: 'live',
        PORT: '3002',
        DASHBOARD_BIND_HOST: '0.0.0.0',
        MOMENTUM_ENABLED: 'true',
        MOMENTUM_ENABLED_CHAINS: 'kucoin',
        SWING_ENABLED: 'false',
        BSC_FLOW_BREAKOUT_ENABLED: 'false',
        BASE_DEX_MOMENTUM_RECLAIM_ENABLED: 'false',
        SOLANA_BULL_FLAG_V2_ENABLED: 'false',
        BACKES_SWING_ENABLED: 'false',
        BULL_FLAG_ENABLED: 'true',
        BULL_FLAG_ENABLED_CHAINS: 'kucoin',
        BULL_FLAG_MAX_CONCURRENT_POSITIONS: '1',
        BULL_FLAG_RISK_PCT_BASE: '0.20',
        BULL_FLAG_RISK_PCT_APLUS: '0.20',
        BULL_FLAG_EXIT_CHECK_MINUTES: '5',
        LIVE_BSC_ENTRIES_ENABLED: 'false',
        BSC_MOMENTUM_HEAT_ALLOWANCE_PCT: '60',
        BSC_MAX_CONSECUTIVE_LOSSES: '8',
        LEARNING_ENABLED: 'false',
        SQL_TELEMETRY_FLUSH_MS: '3000',
        MIN_LIQUIDITY_USD: '5000',
        PRE_TRADE_CONTRACT_MODE: 'enforce',
        BOT_MIN_SCHEMA_VERSION: '17',
        SQL_AUTO_PRUNE_ENABLED: 'true',
        SQL_AUTO_PRUNE_INTERVAL_MS: '3600000',
        PRE_TRADE_CONTRACT_MODE: 'enforce',
        BOT_MIN_SCHEMA_VERSION: '17',
      },
      env_production: {
        NODE_ENV: 'production',
        BOT_PROFILE: 'live',
        PORT: '3002',
        DASHBOARD_BIND_HOST: '0.0.0.0',
        MOMENTUM_ENABLED: 'true',
        MOMENTUM_ENABLED_CHAINS: 'kucoin',
        SWING_ENABLED: 'false',
        BSC_FLOW_BREAKOUT_ENABLED: 'false',
        BASE_DEX_MOMENTUM_RECLAIM_ENABLED: 'false',
        SOLANA_BULL_FLAG_V2_ENABLED: 'false',
        BACKES_SWING_ENABLED: 'false',
        BULL_FLAG_ENABLED: 'true',
        BULL_FLAG_ENABLED_CHAINS: 'kucoin',
        BULL_FLAG_MAX_CONCURRENT_POSITIONS: '1',
        BULL_FLAG_RISK_PCT_BASE: '0.20',
        BULL_FLAG_RISK_PCT_APLUS: '0.20',
        BULL_FLAG_EXIT_CHECK_MINUTES: '5',
        LIVE_BSC_ENTRIES_ENABLED: 'false',
        BSC_MOMENTUM_HEAT_ALLOWANCE_PCT: '60',
        BSC_MAX_CONSECUTIVE_LOSSES: '8',
        LEARNING_ENABLED: 'false',
        SQL_TELEMETRY_FLUSH_MS: '3000',
        MIN_LIQUIDITY_USD: '5000',
        PRE_TRADE_CONTRACT_MODE: 'enforce',
        BOT_MIN_SCHEMA_VERSION: '17',
        SQL_AUTO_PRUNE_ENABLED: 'true',
        SQL_AUTO_PRUNE_INTERVAL_MS: '3600000',
        PRE_TRADE_CONTRACT_MODE: 'enforce',
        BOT_MIN_SCHEMA_VERSION: '17',
      },
    },
    {
      name: 'dex-bot-paper',
      cwd: PAPER_WORKTREE_PATH,
      script: 'src/index.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      kill_timeout: 10000,
      listen_timeout: 15000,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PAPER_TRADING: 'true',
        PORT: '3001',
        DASHBOARD_BIND_HOST: '0.0.0.0',
        BOT_PROFILE: 'paper',
        BOT_DATA_DIR: 'data',
        MOMENTUM_ENABLED: 'true',
        MOMENTUM_ENABLED_CHAINS: 'solana,bsc,kucoin',
        SWING_ENABLED: 'false',
        BSC_FLOW_BREAKOUT_ENABLED: 'true',
        BSC_FLOW_BREAKOUT_ENABLED_CHAINS: 'bsc',
        BASE_DEX_MOMENTUM_RECLAIM_ENABLED: 'true',
        BASE_DEX_MOMENTUM_RECLAIM_ENABLED_CHAINS: 'base',
        SOLANA_BULL_FLAG_V2_ENABLED: 'true',
        SOLANA_BULL_FLAG_V2_ENABLED_CHAINS: 'solana',
        BACKES_SWING_ENABLED: 'true',
        BACKES_SWING_ENABLED_CHAINS: 'kucoin',
        BULL_FLAG_ENABLED: 'true',
        BULL_FLAG_ENABLED_CHAINS: 'kucoin',
        SELF_EVOLUTION_ALLOW_LIVE_APPLY: 'false',
        SELF_EVOLUTION_UNSAFE_EXPERIMENTAL: 'false',
        SQL_AUTO_PRUNE_ENABLED: 'true',
        SQL_AUTO_PRUNE_INTERVAL_MS: '3600000',
        PRE_TRADE_CONTRACT_MODE: 'enforce',
        BOT_MIN_SCHEMA_VERSION: '17',
      },
      env_production: {
        NODE_ENV: 'production',
        PAPER_TRADING: 'true',
        PORT: '3001',
        DASHBOARD_BIND_HOST: '0.0.0.0',
        BOT_PROFILE: 'paper',
        BOT_DATA_DIR: 'data',
        MOMENTUM_ENABLED: 'true',
        MOMENTUM_ENABLED_CHAINS: 'solana,bsc,kucoin',
        SWING_ENABLED: 'false',
        BSC_FLOW_BREAKOUT_ENABLED: 'true',
        BSC_FLOW_BREAKOUT_ENABLED_CHAINS: 'bsc',
        BASE_DEX_MOMENTUM_RECLAIM_ENABLED: 'true',
        BASE_DEX_MOMENTUM_RECLAIM_ENABLED_CHAINS: 'base',
        SOLANA_BULL_FLAG_V2_ENABLED: 'true',
        SOLANA_BULL_FLAG_V2_ENABLED_CHAINS: 'solana',
        BACKES_SWING_ENABLED: 'true',
        BACKES_SWING_ENABLED_CHAINS: 'kucoin',
        BULL_FLAG_ENABLED: 'true',
        BULL_FLAG_ENABLED_CHAINS: 'kucoin',
        SELF_EVOLUTION_ALLOW_LIVE_APPLY: 'false',
        SELF_EVOLUTION_UNSAFE_EXPERIMENTAL: 'false',
        SQL_AUTO_PRUNE_ENABLED: 'true',
        SQL_AUTO_PRUNE_INTERVAL_MS: '3600000',
        PRE_TRADE_CONTRACT_MODE: 'enforce',
        BOT_MIN_SCHEMA_VERSION: '17',
      },
    },
  ],
};
