@echo off
cd /d "C:\Users\User_\Desktop\dex-trading-bot-perps"
set PERPS_PAPER_SERVICE_ENABLED=true
set PERPS_PAPER_MARKET_DATA_ENABLED=true
set PERPS_PAPER_SYMBOLS=BTCUSDT,ETHUSDT,SOLUSDT
set PERPS_PAPER_EQUITY_USD=10000
set PERPS_PAPER_LEVERAGE=3
set PERPS_PAPER_SCAN_INTERVAL_MS=900000
set PORT=3010
set PERPS_PAPER_OBSERVATION_DAYS=0
set PERPS_PAPER_STRATEGY_ADMISSION_REQUIRED=true

node src/index.js
exit /b %ERRORLEVEL%
