#!/usr/bin/env node
'use strict';

// Paper bot keep-alive watcher.
//
// Why this exists: the paper process has been dying silently (empty stderr,
// no SIGTERM trail, no V8 OOM trace) while spot + perps survive. Root cause
// is still unknown — likely an external SIGKILL (AV, IDE wrapper, Windows
// job object). Until that's diagnosed, this watcher polls /health on the
// configured port and respawns the bot when 3 consecutive checks fail.
//
// Launch (detached, won't auto-start on boot):
//   node scripts/keep-alive.js &           # bash
//   Start-Process node 'scripts/keep-alive.js' -WindowStyle Hidden -Environment @{...}
//
// Single-instance: writes a lock file with its own PID. Second invocation
// exits if an alive lock-owner is detected. Lock cleared on graceful exit.
//
// Env:
//   PAPER_KEEPALIVE_PORT          (default 3001)
//   PAPER_KEEPALIVE_POLL_MS       (default 30000)
//   PAPER_KEEPALIVE_FAIL_THRESHOLD (default 3)
//   PAPER_KEEPALIVE_BOOT_GRACE_MS (default 60000)  — skip checks while booting
//   NODE_OPTIONS                  — forwarded to spawned paper process

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const http = require('http');

const REPO_ROOT = path.resolve(__dirname, '..');
const LOG_PATH = path.join(REPO_ROOT, 'logs', 'keep-alive.log');
const LOCK_PATH = path.join(REPO_ROOT, 'logs', 'keep-alive.lock');
const STDOUT_PATH = path.join(REPO_ROOT, 'logs', 'stdout.log');
const STDERR_PATH = path.join(REPO_ROOT, 'logs', 'stderr.log');

const PORT = Number(process.env.PAPER_KEEPALIVE_PORT || 3001);
const POLL_MS = Number(process.env.PAPER_KEEPALIVE_POLL_MS || 30000);
const FAIL_THRESHOLD = Number(process.env.PAPER_KEEPALIVE_FAIL_THRESHOLD || 3);
const BOOT_GRACE_MS = Number(process.env.PAPER_KEEPALIVE_BOOT_GRACE_MS || 60000);

function log(message) {
  const line = `[${new Date().toISOString()}] [keep-alive pid=${process.pid}] ${message}`;
  try { fs.appendFileSync(LOG_PATH, line + '\n'); } catch (_) { /* ignore */ }
  // eslint-disable-next-line no-console
  console.log(line);
}

function acquireLock() {
  fs.mkdirSync(path.dirname(LOCK_PATH), { recursive: true });
  if (fs.existsSync(LOCK_PATH)) {
    const existingPid = Number(fs.readFileSync(LOCK_PATH, 'utf8').trim());
    if (Number.isFinite(existingPid) && existingPid > 0) {
      try {
        process.kill(existingPid, 0); // alive check
        log(`another keep-alive already running pid=${existingPid}; exiting`);
        process.exit(0);
      } catch (_err) {
        log(`stale lock from pid=${existingPid}; reclaiming`);
      }
    }
  }
  fs.writeFileSync(LOCK_PATH, String(process.pid));
  process.on('exit', () => {
    try {
      const current = Number(fs.readFileSync(LOCK_PATH, 'utf8').trim());
      if (current === process.pid) fs.unlinkSync(LOCK_PATH);
    } catch (_err) { /* ignore */ }
  });
}

function healthCheck() {
  return new Promise((resolve) => {
    const req = http.get({
      host: '127.0.0.1',
      port: PORT,
      path: '/health',
      timeout: 5000,
    }, (res) => {
      res.resume();
      resolve(res.statusCode === 200);
    });
    req.on('error', () => resolve(false));
    req.on('timeout', () => { req.destroy(); resolve(false); });
  });
}

function spawnPaper() {
  log('spawning paper bot ...');
  // Windows-only path: Node's `spawn(detached:true)` flashes a console window
  // even with windowsHide:true (the new process group briefly inherits a console
  // before detaching). PowerShell Start-Process -WindowStyle Hidden truly
  // creates the child with CREATE_NO_WINDOW + DETACHED_PROCESS in one call.
  //
  // Inline `-Command "..."` with embedded `;`, `@{}`, and quotes fails through
  // Node's Windows argv quoting. Write a temp .ps1 to disk and run with -File,
  // which takes a single path argument and avoids shell-argv mangling entirely.
  const nodeOptions = process.env.NODE_OPTIONS
    || '--max-old-space-size=4096 --heapsnapshot-near-heap-limit=3 --trace-warnings';
  const q = (s) => String(s).replace(/'/g, "''");
  const helperLog = path.join(REPO_ROOT, 'logs', 'spawn-helper.log');
  const ps1Path = path.join(REPO_ROOT, 'logs', 'spawn-paper.ps1');
  // Windows PowerShell 5.1 (default on Win10/11) does NOT support
  // Start-Process -Environment (PS 7.4+ feature). Set env vars in current
  // process scope and let child inherit them. The .ps1 process exits right
  // after Start-Process, so polluting its env has no lingering effect.
  const ps1 = [
    `# Auto-generated by keep-alive.js; do not edit by hand.`,
    `$ErrorActionPreference = 'Stop'`,
    `$helperLog = '${q(helperLog)}'`,
    `Add-Content -Path $helperLog -Value ("$(Get-Date -Format o) helper invoked")`,
    `try {`,
    `  $env:BOT_PROFILE = 'paper'`,
    `  $env:PORT = '${PORT}'`,
    `  $env:NODE_ENV = 'production'`,
    `  $env:NODE_OPTIONS = '${q(nodeOptions)}'`,
    `  $p = Start-Process -FilePath '${q(process.execPath)}' \`
    -ArgumentList 'src/index.js' \`
    -WorkingDirectory '${q(REPO_ROOT)}' \`
    -WindowStyle Hidden \`
    -RedirectStandardOutput '${q(STDOUT_PATH)}' \`
    -RedirectStandardError '${q(STDERR_PATH)}' \`
    -PassThru`,
    `  Add-Content -Path $helperLog -Value ("$(Get-Date -Format o) Start-Process OK pid=" + $p.Id)`,
    `} catch {`,
    `  Add-Content -Path $helperLog -Value ("$(Get-Date -Format o) Start-Process FAILED: " + $_.Exception.Message)`,
    `}`,
    ``,
  ].join('\r\n');
  fs.writeFileSync(ps1Path, ps1);
  const ps = spawn('powershell.exe', ['-NoProfile', '-WindowStyle', 'Hidden', '-ExecutionPolicy', 'Bypass', '-File', ps1Path], {
    cwd: REPO_ROOT,
    stdio: 'ignore',
    detached: true,
    windowsHide: true,
  });
  ps.unref();
  log(`spawn-helper powershell pid=${ps.pid} via ${ps1Path}`);
}

(async function main() {
  acquireLock();
  log(`watcher start port=${PORT} pollMs=${POLL_MS} failThreshold=${FAIL_THRESHOLD}`);

  // If port is already in use, assume paper is already running and skip the
  // initial spawn. Otherwise spawn immediately.
  let consecutiveFails = 0;
  let lastSpawnAt = 0;
  const initialUp = await healthCheck();
  if (!initialUp) {
    lastSpawnAt = Date.now();
    spawnPaper();
    log(`waiting ${BOOT_GRACE_MS}ms boot grace before polling`);
    await new Promise((r) => setTimeout(r, BOOT_GRACE_MS));
  } else {
    log('paper already healthy on initial check; watching');
  }

  // Graceful shutdown on watcher kill.
  for (const sig of ['SIGINT', 'SIGTERM', 'SIGHUP']) {
    process.on(sig, () => { log(`watcher received ${sig}; exiting (paper NOT killed)`); process.exit(0); });
  }

  while (true) {
    await new Promise((r) => setTimeout(r, POLL_MS));
    const ok = await healthCheck();
    if (ok) {
      if (consecutiveFails > 0) log(`recovered after ${consecutiveFails} failed checks`);
      consecutiveFails = 0;
      continue;
    }
    consecutiveFails += 1;
    log(`health check FAILED (${consecutiveFails}/${FAIL_THRESHOLD})`);
    if (consecutiveFails >= FAIL_THRESHOLD) {
      const sinceSpawn = Date.now() - lastSpawnAt;
      if (sinceSpawn < BOOT_GRACE_MS) {
        log(`skipping respawn — still within boot grace (${sinceSpawn}ms < ${BOOT_GRACE_MS}ms)`);
        continue;
      }
      lastSpawnAt = Date.now();
      spawnPaper();
      consecutiveFails = 0;
      log(`waiting ${BOOT_GRACE_MS}ms boot grace before next poll`);
      await new Promise((r) => setTimeout(r, BOOT_GRACE_MS));
    }
  }
})().catch((err) => {
  log(`watcher fatal: ${err?.stack || err?.message || err}`);
  process.exit(1);
});
